language: c
script: meson build && cd ./build && ninja

# Uncomment me if this gets annoying
#
# notifications:
#   email: false

before_install:
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - unzip ninja-linux.zip
  - sudo mv ninja /usr/bin/
install:
  - pip3 install --user meson

addons:
  apt:
    packages:
    - libgmp3-dev
    - libsigsegv-dev
    - openssl
    - libuv1-dev
    - libssl-dev
    - libncurses5-dev
    - g++
    - ragel
    - re2c
    - libcurl4-gnutls-dev
    - python3
    - python3-pip
    - unzip
# before_deploy: "make deb" # TODO
deploy:
  skip_cleanup: true
  provider: releases
  prerelease: true # turn this off for official releases
  api_key:
    secure: V4E7784ECSS3MO6ZIRtang9XwibDyvDYGb0MoSaP2CTlmzIAhdokr4KJFM0qM4KRaaajCdQuqi0lojgOjwdxs7e0GkAwScb33LFxQ7Chj/QkFOY7V1AnSRLR5OsXnazB0nur5aSwvcvnggQ2XW3OeF7zIvGfs9aR97SEz/xCrVE=
  file: ./build/urbit # TODO upload package from before_deploy
  on:
    repo: urbit/urbit
    tags: true
