language: c
script: make && make test # no ./configure

# Uncomment me if this gets annoying
#
# notifications: 
#   email: false 

addons:
  apt:
    packages:
    - libgmp3-dev
    - libsigsegv-dev
    - openssl
    - libssl-dev
    - libncurses5-dev
    - make
    - exuberant-ctags
    - automake
    - autoconf
    - libtool
    - g++
    - ragel
    - cmake
    - re2c
    - libcurl4-gnutls-dev
    - python
# before_deploy: "make deb" # TODO
deploy:
  provider: releases
  api_key:
    secure: adz7cDMVUEgxaX8eFwy0ms77UvG69+gSwBaAn2+Op1PRe1bSG0rl6BWo8R5ZBaSFKBiZu5+92z74b5+N071AQMZJ+IWEMSiI2lrMm+VJF/E/Z5cDndVr1XA/lVzfAblKlS57z/5azeC8c+s0TFIcNRb1SsDGfWjx65wD5yLC5lk=
  file: bin/urbit # TODO upload package from before_deploy
  on:
    repo: ohAitch/urbit
    all_branches: true
