language: c
script: meson build && cd ./build && ninja

# Uncomment me if this gets annoying
#
# notifications:
#   email: false

install:
  - pip3 install meson

addons:
  apt:
    packages:
    - libgmp3-dev
    - libsigsegv-dev
    - openssl
    - libuv-dev
    - libssl-dev
    - libncurses5-dev
    - ninja-build
    - g++
    - ragel
    - re2c
    - libcurl4-gnutls-dev
    - python3
    - python3-pip
# before_deploy: "make deb" # TODO
deploy:
  skip_cleanup: true
  provider: releases
  prerelease: true # turn this off for official releases
  api_key:
    secure: V4E7784ECSS3MO6ZIRtang9XwibDyvDYGb0MoSaP2CTlmzIAhdokr4KJFM0qM4KRaaajCdQuqi0lojgOjwdxs7e0GkAwScb33LFxQ7Chj/QkFOY7V1AnSRLR5OsXnazB0nur5aSwvcvnggQ2XW3OeF7zIvGfs9aR97SEz/xCrVE=
  file: ./build/urbit # TODO upload package from before_deploy
  on:
    repo: urbit/urbit
    tags: true
